### ISSUE TITLE
Dependencies on Xcode?

### ISSUE THREAD

**Issue by zg** [underscoreio/creative-scala#3] opened 2015-02-27 13:41 UTC
$ npm install
    npm WARN package.json eescala@1.0.0 No repository field.
    npm WARN package.json underscore-ebook-template@1.0.0 No repository field.
    underscore-ebook-template@1.0.0 node_modules/underscore-ebook-template
    └── js-yaml@3.2.7 (esprima@2.0.0, argparse@1.0.1)
    $ grunt pdf
    Running "pandoc:pdf" (pandoc) task
    Running shell command: pandoc --smart --output=dist/creative-scala.pdf --template=node_modules/underscore-ebook-template/lib/templates/template.tex --from=markdown+grid_tables+multiline_tables+fenced_code_blocks+fenced_code_attributes+yaml_metadata_block+implicit_figures+header_attributes+definition_lists --latex-engine=xelatex --variable=lib-dir:node_modules/underscore-ebook-template/lib --filter=node_modules/underscore-ebook-template/lib/filters/pdf/callout.coffee --filter=node_modules/underscore-ebook-template/lib/filters/pdf/columns.coffee --filter=node_modules/underscore-ebook-template/lib/filters/pdf/solutions.coffee --filter=node_modules/underscore-ebook-template/lib/filters/pdf/vector-images.coffee --chapters --number-sections --table-of-contents --highlight-style tango --standalone --self-contained --include-before-body=node_modules/underscore-ebook-template/lib/templates/cover-notes.tex src/meta/metadata.yaml src/meta/pdf.yaml src/pages/intro/index.md src/pages/expressions/index.md src/pages/expressions/simple.md src/pages/expressions/images.md src/pages/expressions/take-home-points.md src/pages/declarations/index.md src/pages/declarations/value-declarations.md src/pages/declarations/method-declarations.md src/pages/declarations/color-palette.md src/pages/declarations/take-home-points.md src/pages/fp/index.md src/pages/fp/recursion.md src/pages/fp/functions.md src/pages/fp/take-home-points.md src/pages/collections/index.md src/pages/collections/create.md src/pages/collections/transform.md src/pages/collections/take-home-points.md src/pages/summary/index.md src/pages/quickreference/index.md src/pages/solutions.md src/pages/links.md
    >> p
    >> andoc: Error running filter node_modules/underscore-ebook-template/lib/filters/pdf/callout.coffee
    >> fd:4: hClose: resource vanished (Broken pipe)
    >> Shell command exited with code 83
    Warning: Task "pandoc:pdf" failed. Use --force to continue.

    Aborted due to warnings.

Some issues I ran into following the installation portion of README.md.

**Comment by noelwelsh** [comment] 2015-02-27 15:28
Pandoc is looking for some file that doesn't exist. Unfortunately it doesn't tell us what file. Two questions:

1. Does `grunt html` work ok?
2. Do you have Latex installed on your system?

Thanks for the report.

**Comment by zg** [comment] 2015-02-27 15:33
1.

    $ grunt html                                                
    Running "less:main" (less) task
    File dist/temp/html/main.noembed.css created
    File dist/temp/epub/main.noembed.css created
    
    Running "cssUrlEmbed:main" (cssUrlEmbed) task
    
    Processing source file "dist/temp/html/main.noembed.css"
    3 embeddable URLs found
    
    Processing source file "dist/temp/epub/main.noembed.css"
    3 embeddable URLs found
    >> "node_modules/underscore-ebook-template/lib/templates/images/hero-left-overlay-white.svg" embedded
    >> "node_modules/underscore-ebook-template/lib/templates/images/hero-left-overlay-white.svg" embedded
    >> "node_modules/underscore-ebook-template/lib/templates/images/hero-right-overlay-white.svg" embedded
    >> "node_modules/underscore-ebook-template/lib/templates/images/hero-right-overlay-white.svg" embedded
    >> "node_modules/underscore-ebook-template/lib/templates/images/hero-arrow-overlay-white.svg" embedded
    File "dist/temp/html/main.css" created
    >> "node_modules/underscore-ebook-template/lib/templates/images/hero-arrow-overlay-white.svg" embedded
    File "dist/temp/epub/main.css" created
    
    Running "browserify:main" (browserify) task
    
    Running "pandoc:html" (pandoc) task
    Running shell command: pandoc --smart --output=dist/creative-scala.html --template=node_modules/underscore-ebook-template/lib/templates/template.html --from=markdown+grid_tables+multiline_tables+fenced_code_blocks+fenced_code_attributes+yaml_metadata_block+implicit_figures+header_attributes+definition_lists --latex-engine=xelatex --variable=lib-dir:node_modules/underscore-ebook-template/lib --filter=node_modules/underscore-ebook-template/lib/filters/html/tables.coffee --filter=node_modules/underscore-ebook-template/lib/filters/html/solutions.coffee --filter=node_modules/underscore-ebook-template/lib/filters/html/vector-images.coffee --chapters --number-sections --table-of-contents --highlight-style tango --standalone --self-contained --toc-depth=2 --include-before-body=node_modules/underscore-ebook-template/lib/templates/cover-notes.html src/meta/metadata.yaml src/meta/html.yaml src/pages/intro/index.md src/pages/expressions/index.md src/pages/expressions/simple.md src/pages/expressions/images.md src/pages/expressions/take-home-points.md src/pages/declarations/index.md src/pages/declarations/value-declarations.md src/pages/declarations/method-declarations.md src/pages/declarations/color-palette.md src/pages/declarations/take-home-points.md src/pages/fp/index.md src/pages/fp/recursion.md src/pages/fp/functions.md src/pages/fp/take-home-points.md src/pages/collections/index.md src/pages/collections/create.md src/pages/collections/transform.md src/pages/collections/take-home-points.md src/pages/summary/index.md src/pages/quickreference/index.md src/pages/solutions.md src/pages/links.md
    >> pand
    >> oc: Error running filter node_modules/underscore-ebook-template/lib/filters/html/tables.coffee
    >> fd:4: hClose: resource vanished (Broken pipe)
    >> Shell command exited with code 83
    Warning: Task "pandoc:html" failed. Use --force to continue.
    
    Aborted due to warnings.

2. Yes.

**Comment by zg** [comment] 2015-02-27 15:55
I'm currently installing Xcode to see if this fixes any or all of these issues.

**Comment by davegurnell** [comment] 2015-02-27 16:38
We use some Grunt plugins that depend on C libraries. Xcode is a requirement on OS X for the C compiler.

-- Dave

**Comment by zg** [comment] 2015-02-27 16:40
Still getting this strange "Resource vanished" issue...

    >> nning filter node_modules/underscore-ebook-template/lib/filters/pdf/callout.coffee
    >> fd:4: hClose: resource vanished (Broken pipe)

Perhaps this is an issue with grunt, or...?

**Comment by noelwelsh** [comment] 2015-02-27 17:09
I really don't know, unforunately. It would try `grunt html` as that takes LaTex out of the equation. Then two things you might try:

1. Do all of the files referenced in the pandoc command line exist? 
2. Do you have a `dist` directory and is there anything there?

FWIW, here's the Pandoc version I'm using

```
$ pandoc -v
pandoc 1.13.1
Compiled with texmath 0.8, highlighting-kate 0.5.9.
```

**Comment by zg** [comment] 2015-02-27 17:14
$ pandoc -v
    pandoc 1.13.2
    Compiled with texmath 0.8.0.1, highlighting-kate 0.5.11.1

```
$ grunt html
Running "less:main" (less) task
File dist/temp/html/main.noembed.css created
File dist/temp/epub/main.noembed.css created

Running "cssUrlEmbed:main" (cssUrlEmbed) task

Processing source file "dist/temp/html/main.noembed.css"
3 embeddable URLs found

Processing source file "dist/temp/epub/main.noembed.css"
3 embeddable URLs found
>> "node_modules/underscore-ebook-template/lib/templates/images/hero-left-overlay-white.svg" embedded
>> "node_modules/underscore-ebook-template/lib/templates/images/hero-left-overlay-white.svg" embedded
>> "node_modules/underscore-ebook-template/lib/templates/images/hero-right-overlay-white.svg" embedded
>> "node_modules/underscore-ebook-template/lib/templates/images/hero-right-overlay-white.svg" embedded
>> "node_modules/underscore-ebook-template/lib/templates/images/hero-arrow-overlay-white.svg" embedded
File "dist/temp/epub/main.css" created
>> "node_modules/underscore-ebook-template/lib/templates/images/hero-arrow-overlay-white.svg" embedded
File "dist/temp/html/main.css" created

Running "browserify:main" (browserify) task

Running "pandoc:html" (pandoc) task
Running shell command: pandoc --smart --output=dist/creative-scala.html --template=node_modules/underscore-ebook-template/lib/templates/template.html --from=markdown+grid_tables+multiline_tables+fenced_code_blocks+fenced_code_attributes+yaml_metadata_block+implicit_figures+header_attributes+definition_lists --latex-engine=xelatex --variable=lib-dir:node_modules/underscore-ebook-template/lib --filter=node_modules/underscore-ebook-template/lib/filters/html/tables.coffee --filter=node_modules/underscore-ebook-template/lib/filters/html/solutions.coffee --filter=node_modules/underscore-ebook-template/lib/filters/html/vector-images.coffee --chapters --number-sections --table-of-contents --highlight-style tango --standalone --self-contained --toc-depth=2 --include-before-body=node_modules/underscore-ebook-template/lib/templates/cover-notes.html src/meta/metadata.yaml src/meta/html.yaml src/pages/intro/index.md src/pages/expressions/index.md src/pages/expressions/simple.md src/pages/expressions/images.md src/pages/expressions/take-home-points.md src/pages/declarations/index.md src/pages/declarations/value-declarations.md src/pages/declarations/method-declarations.md src/pages/declarations/color-palette.md src/pages/declarations/take-home-points.md src/pages/fp/index.md src/pages/fp/recursion.md src/pages/fp/functions.md src/pages/fp/take-home-points.md src/pages/collections/index.md src/pages/collections/create.md src/pages/collections/transform.md src/pages/collections/take-home-points.md src/pages/summary/index.md src/pages/quickreference/index.md src/pages/solutions.md src/pages/links.md
>> pandoc: Error ru
>> nning filter node_modules/underscore-ebook-template/lib/filters/html/tables.coffee
>> fd:4: hClose: resource vanished (Broken pipe)
>> Shell command exited with code 83
Warning: Task "pandoc:html" failed. Use --force to continue.

Aborted due to warnings.
```

**Comment by davegurnell** [comment] 2015-03-02 09:31
Progress update. Had a Gitter chat with Zack and tried various things with no progress.

This looks like an error in one of the filter scripts. However, we've run most of the filters directly without being able to reproduce the error.

Zack is using OS X and Pandoc 1.13.2. I'm on Pandoc 1.13.1. I can't recreate this but I may be able to when Homebrew updates to 1.13.2.

Until then I can't progress this without manually installing Pandoc (which I don't want to do while I'm writing books). I'm afraid this ticket will have to go on hold.

**Comment by d6y** [comment] 2015-03-02 10:30
Hey @davegurnell - I realize this issue features Mac/Xcode, and I can't reproduce it there,  but I've fired up an Ubuntu VM and it shows _similar_ behaviour.  I'll be in the office later, so I can show you what I see on this VM.


![ubuntu running 2015-03-02 10-29-48](https://cloud.githubusercontent.com/assets/102661/6439075/19c49c08-c0c7-11e4-9910-e221727578a6.png)

**Comment by davegurnell** [comment] 2015-03-11 12:50
Richard and I found one potential source of error -- users need Coffeescript installed on their path to run the filters needed to prepare the books. I've added `npm install -g coffee-script` to the README. Hopefully this'll fix Zack's problem.

**Comment by zg** [comment] 2015-03-11 13:32
Sorry to keep you on the edge of your seat.  I'll try and check this in
about 30 minutes or so.

**Comment by zg** [comment] 2015-03-11 14:10
```
$ grunt pdf
Running "pandoc:pdf" (pandoc) task
Running shell command: pandoc --smart --output=dist/creative-scala.pdf --template=node_modules/underscore-ebook-template/lib/templates/template.tex --from=markdown+grid_tables+multiline_tables+fenced_code_blocks+fenced_code_attributes+yaml_metadata_block+implicit_figures+header_attributes+definition_lists --latex-engine=xelatex --variable=lib-dir:node_modules/underscore-ebook-template/lib --filter=node_modules/underscore-ebook-template/lib/filters/pdf/callout.coffee --filter=node_modules/underscore-ebook-template/lib/filters/pdf/columns.coffee --filter=node_modules/underscore-ebook-template/lib/filters/pdf/solutions.coffee --filter=node_modules/underscore-ebook-template/lib/filters/pdf/vector-images.coffee --chapters --number-sections --table-of-contents --highlight-style tango --standalone --self-contained --include-before-body=node_modules/underscore-ebook-template/lib/templates/cover-notes.tex src/meta/metadata.yaml src/meta/pdf.yaml src/pages/intro/index.md src/pages/expressions/index.md src/pages/expressions/simple.md src/pages/expressions/images.md src/pages/expressions/take-home-points.md src/pages/declarations/index.md src/pages/declarations/value-declarations.md src/pages/declarations/method-declarations.md src/pages/declarations/color-palette.md src/pages/declarations/take-home-points.md src/pages/fp/index.md src/pages/fp/recursion.md src/pages/fp/functions.md src/pages/fp/take-home-points.md src/pages/collections/index.md src/pages/collections/create.md src/pages/collections/transform.md src/pages/collections/paths.md src/pages/collections/take-home-points.md src/pages/summary/index.md src/pages/quickreference/index.md src/pages/solutions.md src/pages/links.md
Shell command exited with code 0
Done, without errors.
```

:grin:

**Comment by davegurnell** [comment] 2015-03-11 16:00
Great stuff! Closing this ticket.

**Closed by davegurnell** 2015-03-11 16:00 UTC
Labels: help wanted
